name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: aeb920c38144fa480494d5a243bbca60
          TIMEZONE: Asia/Seoul
          
